services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    container_name: inhouse_suite_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - server
    # ports:
    #   - "80:80"
    volumes:
      - dggcrm_production_admin_static_files:/app/staticfiles
    labels:
    - traefik.enable=true
    - traefik.docker.network=coolify
    - "traefik.http.routers.inhouse-nginx.rule=Host(`house.digitalgroundgame.org`) && PathPrefix(`/`)"
    - traefik.http.routers.inhouse-nginx.entryPoints=http
    - traefik.http.services.inhouse-nginx.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: journald


  frontend:
    build:
      context: .
      dockerfile: ./compose/production/application/Dockerfile
    image: inhouse_suite_frontend
    container_name: inhouse_suite_frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=${BACKEND_URL}
    env_file:
      - path: ./.envs/.production/.frontend
        required: false
    expose:
      - "3030"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3030/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    logging:
      driver: journald

  server: &server
    build:
      context: .
      dockerfile: ./compose/production/server/Dockerfile
    image: inhouse_suite_server
    container_name: inhouse_suite_server
    restart: unless-stopped
    volumes:
      - dggcrm_production_admin_static_files:/app/staticfiles
    depends_on:
      - postgres
    env_file:
      - path: ./.envs/.production/.postgres
        required: false
      - path: ./.envs/.production/.discord
        required: false
      - path: ./.envs/.production/.django
        required: false
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DISCORD_BOT_ENABLED=${DISCORD_BOT_ENABLED}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_MEMBERSHIP_TAG=${DISCORD_MEMBERSHIP_TAG}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    expose:
      - "8080"
    command: /start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/api/health/?format=text"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: journald


  postgres:
    image: postgres:18.1
    container_name: inhouse_suite_postgres
    restart: unless-stopped
    volumes:
      - dggcrm_production_postgres_data:/var/lib/postgresql/18/docker
      - dggcrm_production_postgres_data_backups:/backups
    env_file:
      - path: ./.envs/.production/.postgres
        required: false
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: journald

volumes:
  dggcrm_production_postgres_data:
  dggcrm_production_postgres_data_backups:
  dggcrm_production_admin_static_files:
