services:
  nginx:
    image: nginx:1.27-alpine
    container_name: inhouse_suite_nginx
    depends_on:
      - frontend
      - server
    ports:
      - "8090:80"
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - dggcrm_production_admin_static_files:/app/staticfiles
    networks:
      - in_house_suite

  frontend:
    build:
      context: .
      dockerfile: ./compose/production/application/Dockerfile
    image: inhouse_suite_frontend
    container_name: inhouse_suite_frontend
    env_file:
      - path: ./.envs/.production/.frontend
        required: false
    expose:
      - "3030"
    networks:
      - in_house_suite

  server: &server
    build:
      context: .
      dockerfile: ./compose/production/server/Dockerfile
    image: inhouse_suite_server
    container_name: inhouse_suite_server
    volumes:
      - dggcrm_production_admin_static_files:/app/staticfiles
    depends_on:
      - postgres
    env_file:
      - path: ./.envs/.production/.postgres
        required: false
      - path: ./.envs/.production/.discord
        required: false
      - path: ./.envs/.production/.django
        required: false
    ports:
      - "8080:8080"
    command: /start
    networks:
      - in_house_suite


  postgres:
    image: postgres:18.1
    container_name: inhouse_suite_postgres
    volumes:
      - dggcrm_production_postgres_data:/var/lib/postgresql/18/docker
      - dggcrm_production_postgres_data_backups:/backups
    env_file:
      - path: ./.envs/.production/.postgres
        required: false
    expose:
      - "5432"
    networks:
      - in_house_suite

volumes:
  dggcrm_production_postgres_data:
  dggcrm_production_postgres_data_backups:
  dggcrm_production_admin_static_files:

networks:
  in_house_suite:
    driver: bridge
