# Generated by Django 6.0.3 on 2026-04-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('discord_id', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
                'permissions': [('view_all_contacts', 'Can view all contacts'), ('view_contacts_via_event', "Can view event's contacts"), ('change_contacts_via_ticket', "Can edit assigned ticket's contact"), ('change_all_contacts', 'Can edit all contacts')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(default='#9e9e9e', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TagAssignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='contacts.contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='contacts.tag')),
            ],
            options={
                'db_table': 'tag_assignments',
                'indexes': [models.Index(fields=['contact'], name='tag_assignm_contact_8385ff_idx'), models.Index(fields=['tag'], name='tag_assignm_tag_id_8fc3ac_idx')],
                'unique_together': {('contact', 'tag')},
            },
        ),
    ]
