# Generated by Django 6.0.1 on 2026-01-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('view_all_contacts', 'Can view all contacts regardless of assignment')]},
        ),
    ]
