# Generated by Django 6.0.1 on 2026-01-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='server_member',
            field=models.BooleanField(default=False),
        ),
    ]
