# Generated by Django 6.0.1 on 2026-01-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('view_all_contacts', 'Can view all contacts'), ('view_contacts_via_event', "Can view event's contacts"), ('change_contacts_via_ticket', "Can edit assigned ticket's contact"), ('change_all_contacts', 'Can edit all contacts')]},
        ),
    ]
