# Generated by Django 6.0.1 on 2026-01-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_server_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='server_member',
        ),
    ]
