#!/usr/bin/env bash
set -e

echo "Starting container…"

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

echo $POSTGRES_HOST
# Wait for DB
wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

exec "$@"
