worker_processes 1;

events {
  worker_connections 1024;
}

error_log /var/log/nginx/error.log debug;

http {
  rewrite_log on;
  log_format filedebug '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent" '
                       'requested_file="$request_filename"';
  access_log /var/log/nginx/access.log filedebug;

  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  upstream frontend {
    server inhouse_suite_frontend:3030;
  }

  upstream backend {
    server inhouse_suite_server:8080;
  }

  server {
    listen 80;
    server_name _;

    location /health {
      add_header Content-Type text/plain;
      return 200 'healthy';
    }

    # Static Admin files
    location /django/static/ {
      alias /app/staticfiles/; # must match STATIC_ROOT
    }


    # ---- Django routes ----
    location ~ ^/(accounts|api|admin)(/|$) {
      proxy_pass http://backend$request_uri;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ---- Next.js ----
    location / {
      proxy_pass http://frontend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
