# Generated by Django 6.0.3 on 2026-04-03 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_template', models.TextField(blank=True, help_text='Django template for ticket title. Available context: contact, event, user')),
                ('description_template', models.TextField(blank=True, help_text='Django template for ticket description. Available context: contact, event, user')),
                ('ticket_type', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INTRODUCTION', 'Introduction'), ('RECRUIT', 'Recruit for event'), ('CONFIRM', 'Confirm event participation'), ('INTERNAL', 'Internal Call Banking')], default='UNKNOWN', help_text='Default ticket type for tickets created from this template')),
                ('default_priority', models.PositiveSmallIntegerField(choices=[(0, 'P0 - Emergency (Do Now)'), (1, 'P1 - Very High'), (2, 'P2 - High'), (3, 'P3 - Normal'), (4, 'P4 - Low'), (5, 'P5 - Very Low')], default=3, help_text='Default priority for tickets created from this template')),
                ('requires_contact', models.BooleanField(default=False, help_text='Whether tickets created from this template require a contact')),
                ('requires_event', models.BooleanField(default=False, help_text='Whether tickets created from this template require an event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_templates',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_status', models.CharField(choices=[('OPEN', 'Open'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='OPEN', help_text='Current status of this ticket.')),
                ('ticket_type', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INTRODUCTION', 'Introduction'), ('RECRUIT', 'Recruit for event'), ('CONFIRM', 'Confirm event participation'), ('INTERNAL', 'Internal Call Banking')], default='UNKNOWN', help_text='Type for this ticket')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'P0 - Emergency (Do Now)'), (1, 'P1 - Very High'), (2, 'P2 - High'), (3, 'P3 - Normal'), (4, 'P4 - Low'), (5, 'P5 - Very Low')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User ticket is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, help_text='Contact this ticket relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contacts.contact')),
                ('event', models.ForeignKey(blank=True, help_text='Event this ticket relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event')),
                ('reported_by', models.ForeignKey(blank=True, help_text='User that created this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reported', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettemplate')),
            ],
            options={
                'db_table': 'tickets',
                'permissions': [('view_all_tickets', 'Can view any ticket'), ('view_tickets_via_event', 'Can view any ticket associated to an event'), ('claim_ticket', 'Can claim an open ticket'), ('unclaim_ticket', 'Can unclaim a ticket'), ('assign_ticket', 'Can assign a ticket to any user'), ('change_status', 'Can update ticket status'), ('change_all_statuses', "Can update any ticket's status")],
            },
        ),
        migrations.CreateModel(
            name='TicketAsks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('REJECTED', 'Rejected'), ('AGREED', 'Agreed'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('GHOSTED', 'Ghosted')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_asks', to='contacts.contact')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_asks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_comments',
                'ordering': ['created_at'],
                'permissions': [('add_any_comment', 'Can comment on any ticket')],
            },
        ),
    ]
