# Generated by Django 6.0.1 on 2026-01-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_all_tickets', 'Can view any ticket'), ('view_tickets_via_event', 'Can view any ticket associated to an event'), ('claim_ticket', 'Can claim an open ticket'), ('unclaim_ticket', 'Can unclaim a ticket'), ('assign_ticket', 'Can assign a ticket to any user'), ('change_status', 'Can update ticket status'), ('change_all_statuses', "Can update any ticket's status")]},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at'], 'permissions': [('add_any_comment', 'Can comment on any ticket')]},
        ),
    ]
