# Generated by Django 6.0.1 on 2026-03-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_ticket_options_alter_ticketcomment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "title_template",
                    models.TextField(
                        blank=True,
                        help_text="Django template for ticket title. Available context: contact, event, user",
                    ),
                ),
                (
                    "description_template",
                    models.TextField(
                        blank=True,
                        help_text="Django template for ticket description. Available context: contact, event, user",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("INTRODUCTION", "Introduction"),
                            ("RECRUIT", "Recruit for event"),
                            ("CONFIRM", "Confirm event participation"),
                        ],
                        default="UNKNOWN",
                        help_text="Default ticket type for tickets created from this template",
                    ),
                ),
                (
                    "default_priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "P0 - Emergency (Do Now)"),
                            (1, "P1 - Very High"),
                            (2, "P2 - High"),
                            (3, "P3 - Normal"),
                            (4, "P4 - Low"),
                            (5, "P5 - Very Low"),
                        ],
                        default=3,
                        help_text="Default priority for tickets created from this template",
                    ),
                ),
                (
                    "requires_contact",
                    models.BooleanField(
                        default=False, help_text="Whether tickets created from this template require a contact"
                    ),
                ),
                (
                    "requires_event",
                    models.BooleanField(
                        default=False, help_text="Whether tickets created from this template require an event"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ticket_templates",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to create this ticket",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="tickets.tickettemplate",
            ),
        ),
    ]
