# Generated by Django 6.0.1 on 2026-01-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcomment_delete_ticketauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('view_all_tickets', 'Can view all tickets regardless of assignment'), ('view_event_tickets', 'Can view tickets for events the user is assigned to'), ('claim_ticket', 'Can claim tickets'), ('unclaim_ticket', 'Can unclaim tickets'), ('assign_ticket', 'Can assign tickets to other users'), ('comment_any_ticket', 'Can comment on any ticket'), ('change_ticket_status', 'Can change ticket status'), ('manage_ticket_templates', 'Can create and update ticket templates')]},
        ),
    ]
