# Generated by Django 6.0.3 on 2026-04-03 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("location_name", models.CharField(blank=True, max_length=200)),
                ("location_address", models.CharField(blank=True, max_length=300)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[("genric", "Generic"), ("internal", "Internal")],
                        default="genric",
                        help_text="The type of event deciedes the behavior.",
                    ),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="draft",
                        help_text="Current status of this event",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "events",
                "permissions": [
                    ("view_all_events", "Can view all events"),
                    ("view_any_assigned_event", "Can view assigned events regardless of status"),
                    ("change_all_events", "Can edit all events"),
                    ("change_assigned_event", "Can edit assigned events"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventParticipation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("REJECTED", "Rejected"),
                            ("COMMITTED", "Committed"),
                            ("MAYBE", "Maybe"),
                            ("ATTENDED", "Attended"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="UNKNOWN",
                        help_text="Commitment level of the contact for this event",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to="contacts.contact",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="events.event"
                    ),
                ),
            ],
            options={
                "db_table": "event_participations",
                "permissions": [
                    ("view_all_participations", "Can view all participations"),
                    ("change_participation_via_ticket", "Change participation via assigned ticket"),
                    ("change_participation_via_event", "Change participation for joined events"),
                    ("change_all_participations", "Change participation for all events"),
                ],
                "indexes": [
                    models.Index(fields=["event"], name="event_parti_event_i_10b565_idx"),
                    models.Index(fields=["contact"], name="event_parti_contact_7a167a_idx"),
                    models.Index(fields=["status"], name="event_parti_status_800e4a_idx"),
                ],
                "unique_together": {("event", "contact")},
            },
        ),
        migrations.CreateModel(
            name="UsersInEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "users_in_events",
                "ordering": ["-joined_at"],
                "permissions": [
                    ("view_all_usersinevents", "Can view all members in any event"),
                    ("view_usersinevent_via_event", "Can view all members in joined event"),
                    ("change_all_usersinevents", "Modify participations for joined events"),
                    ("change_usersinevent_via_event", "Can add/remove users for assigned events"),
                ],
                "indexes": [
                    models.Index(fields=["user"], name="users_in_ev_user_id_da9cfd_idx"),
                    models.Index(fields=["event"], name="users_in_ev_event_i_e29b4f_idx"),
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
