# Generated by Django 6.0.1 on 2026-01-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('assign_users_to_event', 'Can assign users to events'), ('add_contacts_to_event', 'Can add contacts to events')]},
        ),
    ]
