# Generated by Django 6.0.1 on 2026-01-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_all_events', 'Can view all events'), ('view_any_assigned_event', 'Can view assigned events regardless of status'), ('change_all_events', 'Can edit all events'), ('change_assigned_event', 'Can edit assigned events')]},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'permissions': [('view_all_participations', 'Can view all participations'), ('change_participation_via_ticket', 'Change participation via assigned ticket'), ('change_participation_via_event', 'Change participation for joined events'), ('change_all_participations', 'Change participation for all events')]},
        ),
        migrations.AlterModelOptions(
            name='usersinevent',
            options={'ordering': ['-joined_at'], 'permissions': [('view_all_usersinevents', 'Can view all members in any event'), ('view_usersinevent_via_event', 'Can view all members in joined event'), ('change_all_usersinevents', 'Modify participations for joined events'), ('change_usersinevent_via_event', 'Can add/remove users for assigned events')]},
        ),
    ]
