# Generated by Django 6.0.2 on 2026-02-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventparticipation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_address',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
