# Generated by Django 6.0.4 on 2026-04-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discord_event_id', models.CharField(help_text='Discord scheduled event ID (snowflake)', max_length=64, unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_tracker_discord_id', models.CharField(help_text='Discord user ID of the organizer who ran the tracking command', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staged_events',
                'indexes': [models.Index(fields=['event_tracker_discord_id'], name='staged_even_event_t_d01e78_idx')],
            },
        ),
        migrations.CreateModel(
            name='StagedEventParticipation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discord_id', models.CharField(max_length=64)),
                ('discord_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('REJECTED', 'Rejected'), ('COMMITTED', 'Committed'), ('MAYBE', 'Maybe'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, help_text='Set when promoted into a real EventParticipation row', null=True)),
                ('staged_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.stagedevent')),
            ],
            options={
                'db_table': 'staged_event_participations',
                'indexes': [models.Index(fields=['discord_id'], name='staged_even_discord_1f0bef_idx'), models.Index(condition=models.Q(('imported_at__isnull', True)), fields=['staged_event'], name='staged_part_pending_idx')],
                'unique_together': {('staged_event', 'discord_id')},
            },
        ),
    ]
