# Generated by Django 6.0.4 on 2026-04-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_stagedevent_stagedeventparticipation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagedevent',
            options={'permissions': [('record_attendance', 'Can record attendance via Discord')]},
        ),
    ]
