# Generated by Django 6.0.4 on 2026-04-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_tracker_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anonymous_attendee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='anonymous_attendees_detail',
            field=models.JSONField(default=list),
        ),
    ]
